// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package hw

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// FirstGRPCClient is the client API for FirstGRPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FirstGRPCClient interface {
	FirstCall(ctx context.Context, in *FirstRequest, opts ...grpc.CallOption) (*FirstResponse, error)
}

type firstGRPCClient struct {
	cc grpc.ClientConnInterface
}

func NewFirstGRPCClient(cc grpc.ClientConnInterface) FirstGRPCClient {
	return &firstGRPCClient{cc}
}

func (c *firstGRPCClient) FirstCall(ctx context.Context, in *FirstRequest, opts ...grpc.CallOption) (*FirstResponse, error) {
	out := new(FirstResponse)
	err := c.cc.Invoke(ctx, "/hw.FirstGRPC/FirstCall", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FirstGRPCServer is the server API for FirstGRPC service.
// All implementations must embed UnimplementedFirstGRPCServer
// for forward compatibility
type FirstGRPCServer interface {
	FirstCall(context.Context, *FirstRequest) (*FirstResponse, error)
	mustEmbedUnimplementedFirstGRPCServer()
}

// UnimplementedFirstGRPCServer must be embedded to have forward compatible implementations.
type UnimplementedFirstGRPCServer struct {
}

func (UnimplementedFirstGRPCServer) FirstCall(context.Context, *FirstRequest) (*FirstResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FirstCall not implemented")
}
func (UnimplementedFirstGRPCServer) mustEmbedUnimplementedFirstGRPCServer() {}

// UnsafeFirstGRPCServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FirstGRPCServer will
// result in compilation errors.
type UnsafeFirstGRPCServer interface {
	mustEmbedUnimplementedFirstGRPCServer()
}

func RegisterFirstGRPCServer(s grpc.ServiceRegistrar, srv FirstGRPCServer) {
	s.RegisterService(&FirstGRPC_ServiceDesc, srv)
}

func _FirstGRPC_FirstCall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FirstRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FirstGRPCServer).FirstCall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hw.FirstGRPC/FirstCall",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FirstGRPCServer).FirstCall(ctx, req.(*FirstRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FirstGRPC_ServiceDesc is the grpc.ServiceDesc for FirstGRPC service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FirstGRPC_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hw.FirstGRPC",
	HandlerType: (*FirstGRPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FirstCall",
			Handler:    _FirstGRPC_FirstCall_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hw.proto",
}
